export const LIVE_CITY_COUNT = 24;

export const DL_ASSISTANCE_NAMED_CITY_COUNT = 8;
export const DL_ASSISTANCE_OTHER_CITY_COUNT =
  LIVE_CITY_COUNT - DL_ASSISTANCE_NAMED_CITY_COUNT;

export const LISTING_FEATURED_CITY_COUNT = 6;
export const LISTING_OTHER_CITY_COUNT =
  LIVE_CITY_COUNT - LISTING_FEATURED_CITY_COUNT;
